DimwoodTown_Rivals_House_1F_MapScripts::
	.byte 0
	
DimwoodTown_Rivals_House_1F_EventScript_RivalSecondGuess::
	msgbox DimwoodTown_Rivals_House_1F_Text_RivalSecondGuess, MSGBOX_NPC
	end

DimwoodTown_Rivals_House_1F_EventScript_RivalStarterGet::
	msgbox DimwoodTown_Rivals_House_1F_Text_RivalStarterGet, MSGBOX_NPC
	end

DimwoodTown_Rivals_House_1F_Text_RivalSecondGuess:
	.string "THOMAS tends to second guess himself,\n"
	.string "but that doesn't mean he lacks resolve!$"

DimwoodTown_Rivals_House_1F_Text_RivalStarterGet:
	.string "It was ever so nice of the professor to\n"
	.string "give THOMAS his first POKéMON,\l"
	.string "and a starter POKéMON at that.$"
